config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end
  resources :posts, except: [:index, :new] do
    resources :comments, only: :new
    member do
      post "upvote"
      post "downvote"
    end
  end

  resources :comments, except: [:new] do
    member do
      post "upvote"
      post "downvote"
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :post
  belongs_to(
    :author,
    class_name: "User"
  )

  belongs_to(
    :parent_comment,
    class_name: "Comment"
  )

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )

  has_many :votes, as: :votable

  def vote_total
    self.votes.inject(0) { |sum, vote| sum + vote.value }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: :show
  before_action :require_author, only: [:edit, :update]

  def new
    @comment = Comment.new(post_id: params[:post_id])
    render :new
  end

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:notices] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post_id)
    end
  end

  def show
    @parent_comment = Comment.find(params[:id])
    @child_comment = @parent_comment
      .child_comments
      .new(post_id: @parent_comment.post_id)

    render :show
  end

  def upvote
    comment = Comment.find(params[:id])
    comment.votes.create(value: 1)

    redirect_to post_url(comment.post)
  end

  def downvote
    comment = Comment.find(params[:id])
    comment.votes.create(value: -1)

    redirect_to post_url(comment.post)
  end

  private

  def comment_params
    params.require(:comment)
      .permit(:content, :post_id, :parent_comment_id)
  end

  def require_author
    comment = Comment.find(params[:id])
    
    redirect_to comment_url(comment) if comment.author != current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post">
  <%= authenticity_token %>
  <input
    type="hidden"
    name="comment[post_id]"
    value="<%= comment.post_id %>">
    <input
      type="hidden"
      name="comment[parent_comment_id]"
      value="<%= comment.parent_comment_id %>">

  <label for="comment_content">Comment:</label><br>
  <textarea name="comment[content]" id="comment_content"><%= comment.content %></textarea>
  <br>

  <button>Submit</button>
</form>

<form action="<%= post_url(comment.post_id) %>" method="get">
  <button>Cancel</button>
</form>

app/views/comments/new.html.erb
<%= render "posts/show", post: @comment.post %>
<%= flash_messages %>
<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<%= render "posts/show", post: @parent_comment.post %>

<%= @parent_comment.content %>
<br>

<p>Posted by: <%= @parent_comment.author %><br>
<%= time_ago_in_words(@parent_comment.created_at) %> ago
</p>

Reply:
<%= render "form", comment: @child_comment %>