config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end
  resources :posts, except: [:index, :new] do
    resources :comments, only: :new
    member do
      post "upvote"
      post "downvote"
    end
  end

  resources :comments, except: [:new] do
    member do
      post "upvote"
      post "downvote"
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator, class_name: "User"
  has_many :post_subs
  has_many :posts, through: :post_subs

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :require_moderator, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      flash[:notices] = ["Successfully created #{@sub.title}!"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_user.subs.find_by_id(params[:id])
  end

  def update
    @sub = current_user.subs.find_by_id(params[:id])

    if @sub.update(sub_params)
      flash[:notices] = ["Successfully updated #{@sub.title}!"]
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    join_votes =
      "LEFT OUTER JOIN votes \
        ON votes.votable_id = posts.id \
        AND votes.votable_type = 'Post'"

    @posts = @sub.posts.includes(:votes)
      .joins(join_votes)
      .group("posts.id")
      .order("COALESCE(SUM(votes.value), 0) DESC")

    render :show
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy

    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    sub = Sub.find(params[:id])

    redirect_to subs_url if current_user != sub.moderator
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% button_text = sub.persisted? ? "Update" : "Create Sub" %>

<form action="<%= action_url %>" method="post">
  <%= authenticity_token %>

  <p><label for="sub_title">Sub Name:</label></p>
  <input
    type="text"
    name="sub[title]"
    id="sub_title"
    value="<%= sub.title %>">
  <br>

  <p><label for="sub_description">Description:</label></p>
  <input
    type="text"
    name="sub[description]"
    id="sub_description"
    value="<%= sub.description %>">
  <br>

  <button><%= button_text %></button>
</form>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<%= flash_messages %>

<%= button_to "Delete", sub_url(@sub),
  method: :delete,
  data: {
  confirm: "Are you sure you want to delete this sub?"
} %>

<%= render "form", sub: @sub %>

<form action="<%= sub_url(@sub) %>" method="get">
  <button>Cancel</button>
</form>

app/views/subs/index.html.erb
<%= flash_messages %>
<h1>Frontpage</h1>


<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Create a New Sub!</a>

app/views/subs/new.html.erb
<h1>Create New Sub:</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<%= flash_messages %>

<h1><%= @sub.title %></h1>
<h4><%= @sub.description %></h4>
<h4>Moderator: <%= @sub.moderator %></h4>

<ul>
  <% @posts.each do |post| %>
    <li>(<%= post.vote_total %>)

      <form action="<%= upvote_post_url(post) %>" method="post">
        <input type="hidden" name="sub_id" value="<%= params[:id] %>">
        <%= authenticity_token %>
        <button>+</button>
      </form>

      <form action="<%= downvote_post_url(post) %>" method="post">
        <%= authenticity_token %>
        <input type="hidden" name="sub_id" value="<%= params[:id] %>">
        <button>-</button>
      </form>

      <a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_sub_post_url(@sub) %>">New Post</a><br>

<% if @sub.moderator == current_user %>
  <a href="<%= edit_sub_url(@sub) %>">Edit</a><br>
<% end %>