config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: :new
  end
  resources :posts, except: [:index, :new] do
    resources :comments, only: :new
    member do
      post "upvote"
      post "downvote"
    end
  end

  resources :comments, except: [:new] do
    member do
      post "upvote"
      post "downvote"
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  belongs_to(
    :author,
    class_name: "User"
  )

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments
  has_many :votes, as: :votable

  def top_level_comments
    self.comments.where(parent_comment_id: nil)
  end

  def comments_by_parent_id
    result = Hash.new { |h,k| h[k] = [] }

    join_votes =
      "LEFT OUTER JOIN votes \
        ON (votes.votable_id = comments.id \
        AND votes.votable_type = 'Comment')"

    self.comments.includes(:votes)
      .joins(join_votes)
      .group("comments.id")
      .order("COALESCE(SUM(votes.value), 0) DESC")
      .includes(:author).each do |comment|
        result[comment.parent_comment_id] << comment
      end

    result
  end

  def vote_total
    self.votes.inject(0) { |sum, vote| sum + vote.value }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: :show
  before_action :require_author, only: [:edit, :update, :destroy]

  def new
    @post = Post.new(sub_ids: [params[:sub_id]])
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy

    redirect_to subs_url
  end

  def upvote
    post = Post.find(params[:id])
    post.votes.create(value: 1)

    redirect_to sub_url(params[:sub_id])
  end

  def downvote
    post = Post.find(params[:id])
    post.votes.create(value: -1)

    redirect_to sub_url(params[:sub_id])
  end

  private

  def post_params
    params.require(:post)
      .permit(:title, :content, :url, :sub_ids => [])
  end

  def require_author
    post = Post.find(params[:id])

    redirect_to sub_url(post) if current_user != post.author
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<ul>
  <li>
    <h5><%= comment.content %></h5>
    <br>

      (<%= comment.vote_total %>)

       <form action="<%= upvote_comment_url(comment) %>" method="post">
         <%= authenticity_token %>
         <button>+</button>
       </form>

       <form action="<%= downvote_comment_url(comment) %>" method="post">
         <%= authenticity_token %>
         <input type="hidden" name="sub_id" value="<%= params[:id] %>">
         <button>-</button>
       </form>

     by <%= comment.author %><br>

    <%= time_ago_in_words(comment.created_at) %> ago
    <a href="<%= comment_url(comment) %>">Reply</a>

  </li>
    <% comments_by_parent_id[comment.id].each do |c2| %>
      <%= render "comments", { comment: c2, comments_by_parent_id: comments_by_parent_id } %>
    <% end %>
</ul>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% button_text = post.persisted? ? "Update" : "Submit" %>

  <form action="<%= action_url %>" method="post">
    <%= authenticity_token %>
    <% if post.persisted? %>
      <%= hidden_patch %>
    <% end %>

    <p><label for="post_title">Title:</label></p>
    <input
      type="text"
      name="post[title]"
      id="post_title"
      value="<%= post.title %>">
    <br>

    <p><label for="post_url">Link:</label></p>
    <input
      type="text"
      name="post[url]"
      id="post_url"
      value="<%= post.url %>">
    <br>

    <p>Select Subs:</p>
    <% Sub.all.each do |sub| %>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
        <label><%= sub.title %></label><br>
    <% end %>

    <p><label for="post_content">Text (optional):</label></p>
    <textarea name="post[content]" id="post_content"><%= post.content %></textarea><br>

    <button><%= button_text %></button>
  </form>

app/views/posts/_show.html.erb
<h1><%= post.title %></h1>
<h4><%= post.author %></h4>

<a href="<%= post.url %>"><%= post.url %></a><br>
<%= post.content %>
<br>

<p>
  Posted by: <%= post.author %>
  <br>
  <%= time_ago_in_words(post.created_at) %> ago
</p>

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

<%= render "form", post: @post %>

<form action="<%= sub_url(@post.sub_ids.first) %>" method="get">
  <button>Cancel</button>
</form>

app/views/posts/new.html.erb
<h1>Submit a Post!</h1>

<%= flash_messages %>
<%= render "form", post: @post %>

<form action="<%= sub_url(params[:sub_id]) %>" method="get">
  <button>Cancel</button>
</form>

app/views/posts/show.html.erb
<%= render "show", post: @post %>

<% if @post.author == current_user %>
  <a href="<%= edit_post_url(@post) %>">Edit</a><br>
<% end %>

<form action="<%= post_url(@post) %>" method="post">
  <%= authenticity_token %>
  <%= hidden_delete %>
  <input type="hidden" name="sub_id" value="">
  <button>Delete</button>
</form>

<a href="<%= new_post_comment_url(@post) %>">Comment</a><br>
<%= flash_messages %>

<% @comments_by_parent_id[nil].each do |top_level_comment| %>
  <%= render "comments",
  { :comment => top_level_comment,
    comments_by_parent_id: @comments_by_parent_id } %>
<% end %>